// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqkzfytbofvpxvipicgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxa3pmeXRib2Z2cHh2aXBpY2dnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5OTM3NzksImV4cCI6MjA3MjU2OTc3OX0.69g1E2ZdBqHVdw8S8WjrvnA2D1aRTyT2p4I6etiwKV8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});